author: Daniel Rampelt
database: false
description: Exchange your emeralds for in-game money or the other way around. (Uses
  vault)
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: ca.drmc.emeraldexchange.EmeraldExchange
name: EmeraldExchange
startup: postworld
url: http://drmc.ca/
version: '1.0.2'
depend: [Vault]
commands:
    ee:
        description: Buy or sell emeralds
        usage: /ee <buy|sell|price> [amount]
permissions:
    ee.*:
        description: Access to all commands
        children:
            ee.buy: true
            ee.sell: true
            ee.price: true
    ee.buy:
        description: Access to /ee buy
        default: true
    ee.sell:
        description: Access to /ee sell
        default: true
    ee.price:
        description: Access to /ee price
        default: true